### PR TITLE
Fix Week numbering and starter file of Week 2 design quiz

### PR DESCRIPTION
**Pull request by pulkitkrishna00**
This PR does two things:

- Fix the week numbering. SPD uses a slightly different week numbering that HtC courses. The repo used the HtC numbering. This PR fixes that.

- Fix the Week 2 design quiz starter file. The starter file present in the repo (which was taken from zip file on discord) had solution in it. This PR replaces it with a pristine starter file.

### CODE REVIEW

**Comment by waciumawanjohi** [comment]
The quiz starter file was human readable and now is not. Is it possible to remove the answer and preserve the readability?

**Comment by pulkitkrishna00** [comment]
It is possible, but that would mean manually modifying the file to remove the comment box and adding back its contents as normal comment. The same can be done with all the starter files, but it is lots of manual work.

I think it would be better if we leave the starter files unmodified, to avoid any confusion.

**Comment by waciumawanjohi** [comment]
> leave the starter files unmodified

Do you mean we should not merge this PR? Or that the Quiz starter is from somewhere else and this PR leaves it unmodified? Or something else?

**Comment by pulkitkrishna00** [comment]
The quiz starter added in this PR is from HtC course (where the link still works). I meant merging this PR without modifying that file.

**Comment by waciumawanjohi** [comment]
Hmm... A quick perusal demonstrates that this is far from the only starter file that isn't human readable. Something to address on another day.

**Comment by pulkitkrishna00** [comment]
Some files can be made readable, but most cannot be made readable. Those which have images embedded in them (which is almost all of them), cannot be made readable without significant modifications.

**Pull request merged**
